language: go
go:
  - 1.22.0

os:
  - linux
  - windows

env:
  global:
    - MPV_VERSION=latest
    - YT_DLP_VERSION=latest

branches:
  only:
    - main
    - dev

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sudo apt-get update;
    sudo apt-get install -y mpv;
    sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp;
    sudo chmod a+rx /usr/local/bin/yt-dlp;
    fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    choco install mpv;
    choco install yt-dlp;
    fi
  - go get -v -t -d ./...

script:
  - go test -v ./...
