name: GoAnime CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.6' # Set the Go version to the latest stable version.

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install fzf
        run: |
          wget -O fzf.tar.gz "https://github.com/junegunn/fzf-bin/releases/latest/download/fzf-linux_amd64.tgz"
          tar -xzf fzf.tar.gz
          chmod +x fzf
          sudo mv fzf /usr/local/bin/

      - name: Install VLC
        run: |
          sudo apt update
          sudo apt install -y vlc

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -v ./...

      # Add additional steps if needed
