name: GoAnime CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.0' # Set the Go version to the latest stable version.

      - name: Check out code
        uses: actions/checkout@v3

     

      - name: Install VLC
        run: |
          sudo apt update
          sudo apt install -y vlc

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -v ./...

      # Add additional steps if needed
